#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : R-winch
Version  : 0.1.1
Release  : 35
URL      : https://cran.r-project.org/src/contrib/winch_0.1.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/winch_0.1.1.tar.gz
Summary  : Portable Native and Joint Stack Traces
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0
Requires: R-winch-lib = %{version}-%{release}
Requires: R-winch-license = %{version}-%{release}
Requires: R-lifecycle
Requires: R-procmaps
BuildRequires : R-lifecycle
BuildRequires : R-procmaps
BuildRequires : buildreq-R

%description
stack trace for easier debugging of R packages with native code.

%package lib
Summary: lib components for the R-winch package.
Group: Libraries
Requires: R-winch-license = %{version}-%{release}

%description lib
lib components for the R-winch package.


%package license
Summary: license components for the R-winch package.
Group: Default

%description license
license components for the R-winch package.


%prep
%setup -q -n winch
pushd ..
cp -a winch buildavx2
popd
pushd ..
cp -a winch buildavx512
popd
pushd ..
cp -a winch buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1740105148

%install
export SOURCE_DATE_EPOCH=1740105148
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-winch
cp %{_builddir}/winch/src/vendor/libbacktrace/LICENSE %{buildroot}/usr/share/package-licenses/R-winch/555657fe7ff5be9969fa3387d8e465e0a1afa2f4 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -mapxf -mavx10.1-512 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -mapxf -mavx10.1-512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-va/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/winch/DESCRIPTION
/usr/lib64/R/library/winch/INDEX
/usr/lib64/R/library/winch/Meta/Rd.rds
/usr/lib64/R/library/winch/Meta/features.rds
/usr/lib64/R/library/winch/Meta/hsearch.rds
/usr/lib64/R/library/winch/Meta/links.rds
/usr/lib64/R/library/winch/Meta/nsInfo.rds
/usr/lib64/R/library/winch/Meta/package.rds
/usr/lib64/R/library/winch/Meta/vignette.rds
/usr/lib64/R/library/winch/NAMESPACE
/usr/lib64/R/library/winch/NEWS.md
/usr/lib64/R/library/winch/R/winch
/usr/lib64/R/library/winch/R/winch.rdb
/usr/lib64/R/library/winch/R/winch.rdx
/usr/lib64/R/library/winch/WORDLIST
/usr/lib64/R/library/winch/doc/index.html
/usr/lib64/R/library/winch/doc/report.R
/usr/lib64/R/library/winch/doc/report.Rmd
/usr/lib64/R/library/winch/doc/report.html
/usr/lib64/R/library/winch/help/AnIndex
/usr/lib64/R/library/winch/help/aliases.rds
/usr/lib64/R/library/winch/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/winch/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/winch/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/winch/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/winch/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/winch/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/winch/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/winch/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/winch/help/paths.rds
/usr/lib64/R/library/winch/help/winch.rdb
/usr/lib64/R/library/winch/help/winch.rdx
/usr/lib64/R/library/winch/html/00Index.html
/usr/lib64/R/library/winch/html/R.css
/usr/lib64/R/library/winch/tests/example0.R
/usr/lib64/R/library/winch/tests/example1.R
/usr/lib64/R/library/winch/tests/example2.R
/usr/lib64/R/library/winch/tests/example3.R
/usr/lib64/R/library/winch/tests/example4.R
/usr/lib64/R/library/winch/tests/example5.R
/usr/lib64/R/library/winch/tests/example6.R
/usr/lib64/R/library/winch/tests/example7.R
/usr/lib64/R/library/winch/tests/example8.R
/usr/lib64/R/library/winch/tests/testthat.R
/usr/lib64/R/library/winch/tests/testthat/_snaps/add_trace_back.md
/usr/lib64/R/library/winch/tests/testthat/test-stop.R
/usr/lib64/R/library/winch/tests/testthat/test-trace_back.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/winch/libs/winch.so
/V4/usr/lib64/R/library/winch/libs/winch.so
/VA/usr/lib64/R/library/winch/libs/winch.so
/usr/lib64/R/library/winch/libs/winch.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-winch/555657fe7ff5be9969fa3387d8e465e0a1afa2f4
